### ISSUE TITLE
Why puncBreak()?

### ISSUE THREAD

**Issue by knod** [jamestomasino/read_plugin#16]
Actually, probably not the best place for this question. More of a conversation on the script itself.

**Comment by jamestomasino** [comment]
Not sure what you mean. If a word contains certain types of punctuation within itself, like decimal places, I fake in some whitespace so it can be parsed apart in display.

**Comment by knod** [comment]
I don't quite understand the purpose of splitting and adding a space. If you have the text "2.5", what is the expected display? From what I can see it would be a display of "2." and then, separately, "5", right?

**Comment by jamestomasino** [comment]
It's a good point. When I added it I was facing situations with collapsed sentences "something.Something" and long numbers. Your solution looks interesting. I'm trying it out. Testing the pull now in preparation for updating the plugin.

**Comment by jamestomasino** [comment]
This was addressed in @knod 's last PR. Closing.
