### ISSUE TITLE
Plugin not working with file:// URLs

### ISSUE THREAD

**Issue by qjcg** [jamestomasino/read_plugin#9]
When a local file is being viewed in-browser via file URL (ex: `file:///tmp/test.txt` or `file:///tmp/test.html`), read_plugin seems to not work---if I highlight some text, right click, and do "Read selected text", nothing happens. The plugin bar at the top of the page is not even displayed.

However, if I serve the same files via a local http server, I can use the plugin without issues.

For example, the plugin works fine after I do the following:

```shell
$ cd /tmp
$ python3 -m http.server 7777 &
$ chromium http://localhost:7777/test.txt &
```

**Comment by jamestomasino** [comment]
The best fallback I can offer here is to highlight the text you want to read and use the right-click context menu option. While I could force the icon to read the whole page, I think the context menu is a better solution (and it takes no work on my part!).
